# : replace the title with the name of your restaurant!
title: "Bobby Mo's"
# : write your restaurateur alter ego name below, or your own name
author: Cade Moffatt
#: write your Google Analytics tracking ID below
google_analytics: G-FR5FPCDWPC

theme: minima

collections:
  explorations:
    output: true
